version: '3.7'
services:
  app:
    container_name: learn-docker
    restart: always
    build:
      context: '.'
      args:
        - NODE_ENV=development
    command: npm run dev
    ports:
      - '8000:8000'
